orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

workflows:
  build-deploy:
    jobs:
      - build-and-push-docker-hub:
          context:
            - adams-docker-hub

      - azure-acr/build-and-push-image:
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: example-vote
          tag: $CIRCLE_BRANCH
          context:
            - test-acr-service-principal
jobs:
 build-and-push-docker-hub:
   machine: true

   steps:
     - checkout

     # Login to Docker Hub so we can push later.
     - run: docker login --username $DOCKER_USER --password $DOCKER_PASS

     # build the application image
     - run: docker build -t uffizzicloud/example-vote:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push uffizzicloud/example-vote:$CIRCLE_BRANCH